name: Extract ZIP File

on:
  push:
    paths:
      - 'yourzipfile.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unzip the file
        run: |
          unzip yourzipfile.zip -d ./extracted_files/
          
      - name: Commit extracted files
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Extract zip contents"
          git push
